stages:
  - test
  - build
  - deploy

test:
  stage: test
  tags:
    - k3s
  script:
    - python3 -m venv .venv
    - .venv/bin/pip install -r requirements.txt
    - .venv/bin/pip install pytest
    - .venv/bin/pytest

build:
  stage: build
  tags:
    - k3s
  script:
    - docker build --no-cache -t load-tester-api:latest .
    - docker save load-tester-api:latest -o /tmp/load-tester-api.tar
    - sudo k3s ctr -n k8s.io images rm docker.io/library/load-tester-api:latest || true
    - sudo k3s ctr -n k8s.io images import /tmp/load-tester-api.tar

deploy:
  stage: deploy
  tags:
    - k3s
  variables:
    KUBECONFIG: "/home/gitlab-runner/.kube/config"
  script:
    - kubectl apply -f k8s/deployment.yaml
    - kubectl apply -f k8s/service.yaml
    - kubectl rollout restart deployment/load-tester-api
    - kubectl rollout status deployment/load-tester-api --timeout=60s
